name: Docker Image - Development

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      - # from https://github.com/marketplace/actions/clean-branch-name
        name: Get branch name
        uses: common-fate/branch-name
        id: branch
        with:
          branch: my-branch-name # optional, defaults to the branch the action is running in
          max-length: 32 # optional
          remove-trailing-dash: true # optional, defaults to true

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ava:${{ sgithub.head_ref }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ava:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ava:buildcache,mode=max